CREATE FUNCTION [eliasm_db].PrecioLista(@PRODUCTOID [NVARCHAR](150))
RETURNS NUMERIC(18,2) WITH EXECUTE AS CALLER
AS 
BEGIN
	DECLARE @PRECIO NUMERIC(18,2) = 0;
	
	SELECT @PRECIO = CONVERT(NUMERIC(18,2),P.PrecioVenta) 
	FROM Productos P
	WHERE P.ID = @ProductoId
	
	RETURN @PRECIO
END