CREATE TABLE [dbo].[ComprobantesDetalles] (
    [ComprobanteDetalleId]   INT             NOT NULL,
    [ComprobanteId]          INT             NULL,
    [ProductoId]             NVARCHAR (150)  NULL,
    [ProductoCodigo]         VARCHAR (20)    NULL,
    [ProductoNombre]         VARCHAR (150)   NULL,
    [Cantidad]               INT             NULL,
    [UnidadMedidaId]         NVARCHAR (150)  NULL,
    [UnidadMedidaCodigo]     VARCHAR (5)     NULL,
    [UnidadMedida]           VARCHAR (150)   NULL,
    [CuentaVentaId]          NVARCHAR (150)  NULL,
    [CuentaVentaCodigo]      VARCHAR (5)     NULL,
    [CuentaVenta]            VARCHAR (150)   NULL,
    [PrecioUnitarioSinIva]   NUMERIC (18, 2) NULL,
    [PrecioUnitario]         NUMERIC (18, 2) NULL,
    [SubTotalSinIva]         NUMERIC (18, 2) NULL,
    [SubTotal]               NUMERIC (18, 2) NULL,
    [PorcentajeBonificacion] NUMERIC (18, 2) NULL,
    [ImporteBonificacion]    NUMERIC (18, 2) NULL,
    [AlicuotaIvaId]          NVARCHAR (150)  NULL,
    [AlicuotaIva]            VARCHAR (150)   NULL,
    [AlicuotaProcentaje]     NUMERIC (18, 2) NULL,
    [ImporteNetoNoGravado]   NUMERIC (18, 2) NULL,
    [ImporteExento]          NUMERIC (18, 2) NULL,
    [ImporteNetoGravado]     NUMERIC (18, 2) NULL,
    [Iva27]                  NUMERIC (18, 2) NULL,
    [Iva21]                  NUMERIC (18, 2) NULL,
    [Iva105]                 NUMERIC (18, 2) NULL,
    [Iva5]                   NUMERIC (18, 2) NULL,
    [Iva25]                  NUMERIC (18, 2) NULL,
    [Iva0]                   NUMERIC (18, 2) NULL,
    [FechaAlta]              DATETIME        NULL,
    [UsuarioAlta]            NVARCHAR (256)  NULL,
    CONSTRAINT [PK_ComprobantesDetalles] PRIMARY KEY CLUSTERED ([ComprobanteDetalleId] ASC),
    CONSTRAINT [FK_ComprobantesDetalles_Comprobantes] FOREIGN KEY ([ComprobanteId]) REFERENCES [dbo].[Comprobantes] ([ComprobanteId]),
    CONSTRAINT [FK_ComprobantesDetalles_ParamAlicuotas] FOREIGN KEY ([AlicuotaIvaId]) REFERENCES [dbo].[ParamAlicuotas] ([Id]),
    CONSTRAINT [FK_ComprobantesDetalles_ParamCuentasVentas] FOREIGN KEY ([CuentaVentaId]) REFERENCES [dbo].[ParamCuentasVentas] ([Id]),
    CONSTRAINT [FK_ComprobantesDetalles_ParamUnidadesMedidas] FOREIGN KEY ([UnidadMedidaId]) REFERENCES [dbo].[ParamUnidadesMedidas] ([Id]),
    CONSTRAINT [FK_ComprobantesDetalles_Productos] FOREIGN KEY ([ProductoId]) REFERENCES [dbo].[Productos] ([Id])
);

