CREATE TABLE [dbo].[Comprobantes] (
    [ComprobanteId]         INT             NOT NULL,
    [ComprobanteCodigo]     VARCHAR (20)    NULL,
    [TipoComprobanteId]     INT             NULL,
    [TipoComprobante]       VARCHAR (150)   NULL,
    [TipoComprobanteCodigo] VARCHAR (5)     NULL,
    [Letra]                 CHAR (1)        NULL,
    [PtoVenta]              INT             NULL,
    [Numero]                NUMERIC (12)    NULL,
    [FechaComprobante]      DATETIME        NULL,
    [ConceptoIncluidoId]    INT             NULL,
    [ConceptoIncluido]      VARCHAR (150)   NULL,
    [PeriodoFacturadoDesde] DATETIME        NULL,
    [PeriodoFacturadoHasta] DATETIME        NULL,
    [FechaVencimiento]      DATETIME        NULL,
    [TipoResponsableId]     INT             NULL,
    [TipoResponsable]       VARCHAR (150)   NULL,
    [ClienteId]             INT             NULL,
    [ClienteCodigo]         VARCHAR (20)    NULL,
    [TipoDocumentoId]       NVARCHAR (150)  NULL,
    [TipoDocumento]         VARCHAR (150)   NULL,
    [NroDocumento]          VARCHAR (20)    NULL,
    [Apellido]              VARCHAR (150)   NULL,
    [Nombre]                VARCHAR (150)   NULL,
    [ProvinciaId]           NVARCHAR (150)  NULL,
    [Provincia]             VARCHAR (150)   NULL,
    [LocalidadId]           NVARCHAR (250)  NULL,
    [Localidad]             VARCHAR (150)   NULL,
    [Calle]                 VARCHAR (1000)  NULL,
    [Nro]                   VARCHAR (10)    NULL,
    [OtrasReferencias]      VARCHAR (1000)  NULL,
    [Email]                 VARCHAR (150)   NULL,
    [Telefono]              VARCHAR (50)    NULL,
    [SubTotal]              NUMERIC (18, 2) NULL,
    [ImporteTributos]       NUMERIC (18, 2) NULL,
    [Total]                 NUMERIC (18, 2) NULL,
    [Confirmado]            BIT             NULL,
    [Cobrado]               BIT             NULL,
    [Anulado]               BIT             NULL,
    [FechaAnulacion]        DATETIME        NULL,
    [LetraAnulado]          CHAR (1)        NULL,
    [PtoVtaAnulado]         INT             NULL,
    [NumeroAnulado]         NUMERIC (12)    NULL,
    [Estado]                BIT             NULL,
    [FechaAlta]             DATETIME        NULL,
    [UsuarioAlta]           NVARCHAR (256)  NULL,
    CONSTRAINT [PK_Comprobantes] PRIMARY KEY CLUSTERED ([ComprobanteId] ASC),
    CONSTRAINT [FK_Comprobantes_ParamConceptosIncluidos] FOREIGN KEY ([ConceptoIncluidoId]) REFERENCES [dbo].[ParamConceptosIncluidos] ([ConceptoIncluidoId]),
    CONSTRAINT [FK_Comprobantes_ParamLocalidades] FOREIGN KEY ([LocalidadId]) REFERENCES [dbo].[ParamLocalidades] ([LocalidadId]),
    CONSTRAINT [FK_Comprobantes_ParamProvincias] FOREIGN KEY ([ProvinciaId]) REFERENCES [dbo].[ParamProvincias] ([Id]),
    CONSTRAINT [FK_Comprobantes_ParamTiposComprobantes] FOREIGN KEY ([TipoComprobanteId]) REFERENCES [dbo].[ParamTiposComprobantes] ([TipoComprobanteId]),
    CONSTRAINT [FK_Comprobantes_ParamTiposDocumentos] FOREIGN KEY ([TipoDocumentoId]) REFERENCES [dbo].[ParamTiposDocumentos] ([Id]),
    CONSTRAINT [FK_Comprobantes_ParamTiposResponsables] FOREIGN KEY ([TipoResponsableId]) REFERENCES [dbo].[ParamTiposResponsables] ([TipoResponsableId])
);

