CREATE TABLE [dbo].[ComprobantesFormasPagos] (
    [ComprobanteFormaPagoId] INT             NOT NULL,
    [ComprobanteId]          INT             NULL,
    [FormaPagoId]            INT             NULL,
    [FormaPago]              VARCHAR (150)   NULL,
    [Importe]                NUMERIC (18, 2) NULL,
    [Cuota]                  INT             NULL,
    [ImporteInteres]         NUMERIC (18, 2) NULL,
    [Total]                  NUMERIC (18, 2) NULL,
    [TarjetaId]              INT             NULL,
    [TarjetaNombre]          VARCHAR (150)   NULL,
    [TarjetaCliente]         VARCHAR (300)   NULL,
    [TarjetaNumero]          VARCHAR (16)    NULL,
    [TarjetaVenceMes]        INT             NULL,
    [TarjetaVenceAño]        INT             NULL,
    [TarjetaCodigoSeguridad] INT             NULL,
    [TarjetaEsDebito]        BIT             NULL,
    [ChequeBancoId]          INT             NULL,
    [ChequeBanco]            VARCHAR (150)   NULL,
    [ChequeNumero]           VARCHAR (50)    NULL,
    [ChequeFechaEmision]     DATETIME        NULL,
    [ChequeFechaVencimiento] DATETIME        NULL,
    [ChequeCuit]             VARCHAR (11)    NULL,
    [ChequeNombre]           VARCHAR (300)   NULL,
    [ChequeCuenta]           VARCHAR (50)    NULL,
    [FechaAlta]              DATETIME        NULL,
    [UsuarioAlta]            NVARCHAR (256)  NULL,
    CONSTRAINT [PK_ComprobantesFormasPagos] PRIMARY KEY CLUSTERED ([ComprobanteFormaPagoId] ASC),
    CONSTRAINT [FK_ComprobantesFormasPagos_Comprobantes] FOREIGN KEY ([ComprobanteId]) REFERENCES [dbo].[Comprobantes] ([ComprobanteId])
);

