CREATE TABLE [dbo].[Pedidos] (
    [PedidoId]                    INT             NOT NULL,
    [PedidoCodigo]                VARCHAR (10)    NULL,
    [ClienteId]                   INT             NULL,
    [ClienteCodigo]               VARCHAR (20)    NULL,
    [Apellido]                    VARCHAR (150)   NULL,
    [Nombre]                      VARCHAR (150)   NULL,
    [TipoDocumentoId]             INT             NULL,
    [TipoDocumento]               VARCHAR (150)   NULL,
    [NroDocumento]                VARCHAR (20)    NULL,
    [ProvinciaFacturacionId]      INT             NULL,
    [ProvinciaFacturacion]        VARCHAR (150)   NULL,
    [LocalidadFacturacionId]      INT             NULL,
    [LocalidadFacturacion]        VARCHAR (150)   NULL,
    [CalleFacturacion]            NVARCHAR (500)  NULL,
    [NroCalleFacturacion]         NVARCHAR (8)    NULL,
    [DatosDomicilioFacturacion]   NVARCHAR (200)  NULL,
    [ProvinciaEnvioId]            INT             NULL,
    [ProvinciaEnvio]              VARCHAR (150)   NULL,
    [LocalidadEnvioId]            INT             NULL,
    [LocalidadEnvio]              VARCHAR (150)   NULL,
    [CalleEnvio]                  NVARCHAR (500)  NULL,
    [NroCalleEnvio]               NVARCHAR (8)    NULL,
    [DatosDomicilioEnvio]         NVARCHAR (200)  NULL,
    [TipoCondicionIvaId]          INT             NULL,
    [TipoCondicionIva]            VARCHAR (150)   NULL,
    [FechaEmision]                DATETIME        NULL,
    [FechaVencimiento]            DATETIME        NULL,
    [MontoDescuento]              DECIMAL (15, 2) NULL,
    [MontoExento]                 DECIMAL (15, 2) NULL,
    [MontoGravadoNormal]          DECIMAL (15, 2) NULL,
    [MontoNoGravado]              DECIMAL (15, 2) NULL,
    [MontoGravadoReducido]        DECIMAL (15, 2) NULL,
    [MontoInteres]                DECIMAL (15, 2) NULL,
    [IvaInscriptoNormal]          DECIMAL (15, 2) NULL,
    [IvaNoInscrNormal]            DECIMAL (15, 2) NULL,
    [IvaInscriptoReducido]        DECIMAL (15, 2) NULL,
    [IvaNoInscrReducido]          DECIMAL (15, 2) NULL,
    [MontoGravodo10]              DECIMAL (15, 2) NULL,
    [MontoGravado21]              DECIMAL (15, 2) NULL,
    [MontoGravado27]              DECIMAL (15, 2) NULL,
    [IvaInscripto10]              DECIMAL (15, 2) NULL,
    [IvaInscripto21]              DECIMAL (15, 2) NULL,
    [IvaInscripto27]              DECIMAL (15, 2) NULL,
    [IvaNoInscripto10]            DECIMAL (15, 2) NULL,
    [IvaNoInscripto21]            DECIMAL (15, 2) NULL,
    [IvaNoInscripto27]            DECIMAL (15, 2) NULL,
    [MontoGravodoNormal10]        DECIMAL (15, 2) NULL,
    [MontoGravadoNormal21]        DECIMAL (15, 2) NULL,
    [MontoGravadoNormal27]        DECIMAL (15, 2) NULL,
    [IvaInscriptoNormal10]        DECIMAL (15, 2) NULL,
    [IvaInscriptoNormal21]        DECIMAL (15, 2) NULL,
    [IvaInscriptoNormal27]        DECIMAL (15, 2) NULL,
    [IvaNoInscriptoNormal10]      DECIMAL (15, 2) NULL,
    [IvaNoInscriptoNormal21]      DECIMAL (15, 2) NULL,
    [IvaNoInscriptoNormal27]      DECIMAL (15, 2) NULL,
    [PercepcionIva]               DECIMAL (15, 2) NULL,
    [ImpuestoMunicipal]           DECIMAL (15, 2) NULL,
    [PercepcionImpuestoMunicipal] DECIMAL (15, 2) NULL,
    [TipoConvenioIIBBId]          INT             NULL,
    [FechaVigDesdeIIBB]           DATETIME        NULL,
    [FechaVigHastaIIBB]           DATETIME        NULL,
    [AlicuotaIIBB]                DECIMAL (15, 8) NULL,
    [PercepcionIIBB]              DECIMAL (15, 2) NULL,
    [Total]                       DECIMAL (15, 2) NULL,
    [Facturado]                   BIT             NULL,
    [Observaciones]               NVARCHAR (200)  NULL,
    [Estado]                      BIT             NULL,
    [FechaAlta]                   DATETIME        NULL,
    [UsuarioAlta]                 NVARCHAR (256)  NULL,
    CONSTRAINT [PK_Pedidos] PRIMARY KEY CLUSTERED ([PedidoId] ASC)
);

