CREATE TABLE [dbo].[Presupuestos] (
    [Id]                       NVARCHAR (150)  NOT NULL,
    [Codigo]                   NVARCHAR (150)  NULL,
    [Fecha]                    DATETIME        NULL,
    [FechaVencimiento]         DATETIME        NULL,
    [ClienteId]                NVARCHAR (150)  NULL,
    [TipoResponsableId]        NVARCHAR (150)  NULL,
    [ClienteCategoriaId]       NVARCHAR (150)  NULL,
    [EstadoId]                 NVARCHAR (150)  NULL,
    [DescuentoId]              NVARCHAR (150)  NULL,
    [DescuentoPorcentaje]      NUMERIC (18, 2) NULL,
    [FechaAprobacion]          DATETIME        NULL,
    [FechaRechazo]             DATETIME        NULL,
    [MotivoAprobacionRechazo]  NVARCHAR (500)  NULL,
    [UsuarioAprobacionRechazo] NVARCHAR (450)  NULL,
    [Estado]                   BIT             NULL,
    [FechaAlta]                DATETIME        NULL,
    [UsuarioAlta]              NVARCHAR (450)  NULL,
    [FechaEdit]                DATETIME        NULL,
    [UsuarioEdit]              NVARCHAR (450)  NULL,
    CONSTRAINT [PK_Presupuestos] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Presupuestos_Clientes] FOREIGN KEY ([ClienteId]) REFERENCES [dbo].[Clientes] ([Id]),
    CONSTRAINT [FK_Presupuestos_ParamPresupuestosDescuentos] FOREIGN KEY ([DescuentoId]) REFERENCES [dbo].[ParamPresupuestosDescuentos] ([Id]),
    CONSTRAINT [FK_Presupuestos_ParamPresupuestosEstados] FOREIGN KEY ([EstadoId]) REFERENCES [dbo].[ParamPresupuestosEstados] ([Id]),
    CONSTRAINT [FK_Presupuestos_ParamTiposResponsables] FOREIGN KEY ([TipoResponsableId]) REFERENCES [dbo].[ParamTiposResponsables] ([Id])
);

