CREATE TABLE [eliasm_db].[ProductosZ1] (
    [Id]                  INT             NOT NULL,
    [Codigo]              NVARCHAR (20)   NULL,
    [TipoProductoId]      NVARCHAR (150)  NULL,
    [Producto]            NVARCHAR (150)  NULL,
    [DescripcionCorta]    NVARCHAR (500)  NULL,
    [DescripcionLarga]    NVARCHAR (500)  NULL,
    [CodigoBarra]         NVARCHAR (100)  NULL,
    [Peso]                NUMERIC (18, 2) NULL,
    [DimencionesLongitud] NUMERIC (18, 2) NULL,
    [DimencionesAncho]    NUMERIC (18, 2) NULL,
    [DimencionesAltura]   NUMERIC (18, 2) NULL,
    [CuentaVentaId]       NVARCHAR (150)  NULL,
    [CuentaCompraId]      NVARCHAR (150)  NULL,
    [UnidadMedidaId]      NVARCHAR (150)  NULL,
    [AlicuotaId]          NVARCHAR (150)  NULL,
    [PrecioVenta]         NUMERIC (18, 2) NULL,
    [ProveedorId]         NVARCHAR (150)  NULL,
    [CategoriaId]         NVARCHAR (150)  NULL,
    [ControlaStock]       BIT             NULL,
    [AceptaDescuento]     BIT             NULL,
    [PrecioRebaja]        NUMERIC (18, 2) NULL,
    [RebajaDesde]         DATETIME        NULL,
    [RebajaHasta]         DATETIME        NULL,
    [Estado]              BIT             NULL,
    [FechaAlta]           DATETIME        NULL,
    [UsuarioAlta]         NVARCHAR (256)  NULL,
    CONSTRAINT [PK_ProductosZ1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

