CREATE TABLE [eliasm_db].[VentasRapidas] (
    [Id]                  NVARCHAR (150)  NOT NULL,
    [Codigo]              NVARCHAR (150)  NULL,
    [ComprobanteId]       NVARCHAR (150)  NULL,
    [Fecha]               DATETIME        NULL,
    [FechaVencimiento]    DATETIME        NULL,
    [ClienteId]           NVARCHAR (150)  NULL,
    [ClienteCodigo]       NVARCHAR (50)   NULL,
    [TipoDocumentoId]     NVARCHAR (150)  NULL,
    [TipoDocumentoCodigo] NVARCHAR (5)    NULL,
    [TipoDocumento]       NVARCHAR (15)   NULL,
    [NroDocumento]        NVARCHAR (15)   NULL,
    [CuilCuit]            NVARCHAR (50)   NULL,
    [RazonSocial]         NVARCHAR (300)  NULL,
    [ProvinciaId]         NVARCHAR (150)  NULL,
    [ProvinciaCodigo]     NVARCHAR (5)    NULL,
    [Provincia]           NVARCHAR (150)  NULL,
    [Localidad]           NVARCHAR (150)  NULL,
    [CodigoPostal]        NVARCHAR (10)   NULL,
    [Calle]               NVARCHAR (500)  NULL,
    [CalleNro]            NVARCHAR (50)   NULL,
    [PisoDpto]            NVARCHAR (100)  NULL,
    [OtrasReferencias]    NVARCHAR (500)  NULL,
    [Email]               NVARCHAR (150)  NULL,
    [Telefono]            NVARCHAR (50)   NULL,
    [Celular]             NVARCHAR (50)   NULL,
    [TipoResponsableId]   NVARCHAR (150)  NULL,
    [ClienteCategoriaId]  NVARCHAR (150)  NULL,
    [EstadoId]            NVARCHAR (150)  NULL,
    [DescuentoId]         NVARCHAR (150)  NULL,
    [DescuentoPorcentaje] NUMERIC (18, 2) NULL,
    [DescuentoUsuario]    NVARCHAR (450)  NULL,
    [DescuentoFecha]      DATETIME        NULL,
    [SucursalId]          NVARCHAR (150)  NULL,
    [Estado]              BIT             NULL,
    [FechaAlta]           DATETIME        NULL,
    [UsuarioAlta]         NVARCHAR (450)  NULL,
    [FechaEdit]           DATETIME        NULL,
    [UsuarioEdit]         NVARCHAR (450)  NULL,
    CONSTRAINT [PK_VentasRapidas] PRIMARY KEY CLUSTERED ([Id] ASC)
);

